# Generated by Django 5.1.1 on 2026-09-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_more_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='home_department_id',
            field=models.IntegerField(default=101),
        ),
    ]
